version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "sam-jenkins-demo-us-west-2-subhayandpwc"
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
#image_repositories = ["LambdaFunctionWithAPI=940810086075.dkr.ecr.us-east-1.amazonaws.com/samapp7427b055/lambdafunctionwithapi503f8591repo"]
