version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "sam-test-bucket12"
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["LambdaFunctionWithAPI=public.ecr.aws/u6g5x4z6/cosign-test"]#940810086075.dkr.ecr.us-east-1.amazonaws.com/docker-lambda-testapp"]
